apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Istio
- ../distributions/stacks/ibm/application/istio-1-9-0
# Kubeflow namespace (required)
- ../distributions/stacks/ibm/application/kubeflow-namespace
# Kubeflow Roles (required)
- ../distributions/stacks/ibm/application/kubeflow-roles
# Kubeflow istio resource (required)
- ../distributions/stacks/ibm/application/kubeflow-istio-resources


# Kubeflow Pipelines with Tekton
- ../distributions/stacks/openshift/application/kfp-tekton
# MLX
- ../contrib/mlx/base

