apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mlx-api-access
subjects:
- kind: ServiceAccount
  name: mlx-api
  namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: mlx-api-access
  apiGroup: rbac.authorization.k8s.io
