# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/mlx-deployments
resources:
  - minio.yaml
  - mysql.yaml
  - namespace.yaml
  - k8s-ingress.yaml
  - init-jobs.yaml
  - config.yaml
patchesStrategicMerge:
  - mlx-api-patch.yaml
  - mlx-ui-patch.yaml
configMapGenerator:
- name: mlx-parameters
  literals:
  # Update the credentials for the below fields before apply.
  - ingress-domain=ml-exchange.org
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: ingress-domain
  objref:
    kind: ConfigMap
    name: mlx-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.ingress-domain
configurations:
- params.yaml
